# Generated by Django 2.1.3 on 2018-12-24 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_rating', models.FloatField()),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('p', 'published'), ('u', 'unpublished')], default='p', max_length=2)),
                ('currency', models.DecimalField(decimal_places=2, max_digits=8)),
                ('publish_date_time', models.DateTimeField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MovieInfo.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('genre_details', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subgenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MovieInfo.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='sub_genre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MovieInfo.Subgenre'),
        ),
    ]
