# Generated by Django 2.1.3 on 2018-12-24 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(9.9)]),
        ),
    ]
