# Generated by Django 2.1.4 on 2018-12-25 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieInfo', '0012_auto_20181225_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_name',
        ),
    ]
